# Generated by Django 3.2.8 on 2021-11-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('preciocompra_producto', models.CharField(max_length=50)),
                ('precioventa_producto', models.CharField(max_length=50)),
                ('categoria_producto', models.CharField(max_length=50)),
            ],
        ),
    ]
