# Generated by Django 3.2.8 on 2022-01-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_compra_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compra_proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.proveedor'),
        ),
    ]
