# Generated by Django 3.2.8 on 2021-11-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_auto_20211110_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
