# Generated by Django 3.2.8 on 2022-02-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_auto_20220128_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='caja',
            fields=[
                ('codigo_caja', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=50)),
                ('entrada', models.CharField(max_length=50)),
                ('salida', models.CharField(max_length=50)),
            ],
        ),
    ]
