# Generated by Django 3.2.8 on 2022-02-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='codigo_caja',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
