# Generated by Django 3.2.8 on 2022-02-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_alter_caja_codigo_caja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='entrada',
            new_name='entrada_caja',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='fecha',
            new_name='fecha_caja',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='hora',
            new_name='hora_caja',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='motivo',
            new_name='motivo_caja',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='salida',
            new_name='salida_caja',
        ),
    ]
