# Generated by Django 3.2.8 on 2022-02-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_auto_20220202_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='nombre_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios'),
        ),
    ]
