# Generated by Django 3.2.8 on 2022-01-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('codigo_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('ci_cliente', models.IntegerField()),
                ('telefono_cliente', models.IntegerField()),
                ('direccion_cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
