# Generated by Django 3.2.8 on 2022-02-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_caja_nombre_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='entrada_caja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='salida_caja',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
