# Generated by Django 3.2.8 on 2022-01-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ci_cliente',
        ),
    ]
