# Generated by Django 3.2.8 on 2022-01-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_remove_cliente_ci_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('cogigo_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
