# Generated by Django 3.2.8 on 2022-02-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_auto_20220202_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
