# Generated by Django 3.2.8 on 2022-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_usuarios_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='motivo_caja',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
