# Generated by Django 3.2.8 on 2022-01-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('codigo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('ruc_proveedor', models.CharField(max_length=50)),
                ('Telefono_proveedor', models.IntegerField()),
                ('direccion_proveedor', models.CharField(max_length=50)),
            ],
        ),
    ]
