# Generated by Django 3.2.8 on 2022-02-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_alter_caja_motivo_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='tipo_movi',
            field=models.IntegerField(null=True),
        ),
    ]
