# Generated by Django 3.2.8 on 2022-01-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='cogigo_categoria',
            new_name='codigo_categoria',
        ),
    ]
