# Generated by Django 3.2.8 on 2022-01-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_rename_cogigo_categoria_categoria_codigo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
