# Generated by Django 3.2.8 on 2022-02-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_caja_tipo_movi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='tipo_movi',
            new_name='tipo_mov',
        ),
    ]
