# Generated by Django 3.2.8 on 2022-01-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_alter_categoria_codigo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_productos',
            field=models.IntegerField(max_length=50),
        ),
    ]
