# Generated by Django 3.2.8 on 2022-02-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_rename_tipo_movi_caja_tipo_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='total_caja',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
